version: '3'
services: 
    web:
        stdin_open: true
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
        volumes: 
            - /app/node_modules
            - .:/app
    tests:
        stdin_open: true
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes: 
            - /app/node_modules #skip mapping for this file because it already exists
            - .:/app # create a mapping for everything else. 
        command: ["npm", "run", "test"] # can override default cmd just like how we can do that using run command
        